"""Create TelegramChat model

Revision ID: 9f79dbb86013
Revises: 
Create Date: 2022-11-22 17:50:13.412523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f79dbb86013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chat',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=20), nullable=True),
    sa.Column('receive_fact', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_chat')
    # ### end Alembic commands ###
